### ISSUE TITLE
Could most of this factor out?

### ISSUE THREAD

**Issue by pfrazee** [dominictarr/streamview-links#2]
I was reading through the implementation and it looks like the only link-specific thing is tied up in the emitter:

```js
function links (doc, emit) {
  emit({source: s, dest: d, rel: r, ts: ts})
}
...
StreamviewLinks(dirname, indexes, links, version)
```

If this method didnt emit links, but some other extracted data, wouldnt this be pretty general?

**Comment by dominictarr** [comment]
this is now the case... should rename, really.
